### ISSUE TITLE
Fix url for bootstrap.min.js/css/  and jquery

### ISSUE THREAD

**Issue by elflaco777** [reynososergio/project01#1]
I'll try to fix those urls because in my localhost I cannot see any bootstrap's styles :sa:
I can fix it many errors frm GIT :) and now is moment to start to coding until die hahahahaha

**Comment by elflaco777** [comment]
It's done.

**Comment by JulioCesar1988** [comment]
por que escribis en japones \\

**Comment by reynososergio** [comment]
Ok, wenn Sie fertig sind die TP-BD2 hat mich mit diesem zurück
